/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBtn: typeof import('./src/components/main/layout/ActionBtn.vue')['default']
    ApiCards: typeof import('./src/components/settings/contents/apiCard/apiCards.vue')['default']
    ApiSource: typeof import('./src/components/settings/contents/ApiSource.vue')['default']
    BtnGroup: typeof import('./src/components/settings/utils/BtnGroup.vue')['default']
    ComfirmBox: typeof import('./src/components/utils/ComfirmBox.vue')['default']
    Content: typeof import('./src/components/settings/layout/Content.vue')['default']
    DragBar: typeof import('./src/components/settings/layout/DragBar.vue')['default']
    Header: typeof import('./src/components/main/layout/Header.vue')['default']
    IPInfo: typeof import('./src/components/main/layout/IPInfo.vue')['default']
    MessageBox: typeof import('./src/components/utils/MessageBox.vue')['default']
    Proxy: typeof import('./src/components/settings/contents/Proxy.vue')['default']
    RequestOpt: typeof import('./src/components/settings/contents/RequestOpt.vue')['default']
    SaveBtn: typeof import('./src/components/settings/utils/SaveBtn.vue')['default']
    TestBtn: typeof import('./src/components/settings/utils/TestBtn.vue')['default']
    Theme: typeof import('./src/components/settings/contents/Theme.vue')['default']
    ToolBar: typeof import('./src/components/main/layout/ToolBar.vue')['default']
  }
}
